export const background_color = '#EEEBE4'
export const header_background_color = '#E3E0D9'
export const accent_color = '#5DADC2'
export const dark_text_color = '#1B2020'
export const status_text_font = 'ArialRoundedMTBold'
export const header_font = 'HelveticaNeue-LightItalic'
