export const background_color = '#FFFFFF'
export const light_text_color = '#666666'
export const dark_text_color = '#000000'
export const highlight_color = '#52BDC8'
export const status_text_font = 'Avenir'
